schema_version: 1

context:
  name: pymatgen-core
  version: "2026.7.31"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pymatgen_core-${{ version }}.tar.gz
  sha256: 42407e0b51807de73f01b16c604d1af84e8110feb300934391c048a14196deeb

build:
  number: 2
  skip: match(python, "<=3.10")
  script:
    if: win
    then:
      - set SETUPTOOLS_SCM_PRETEND_VERSION=${{ version }} ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    else:
      - SETUPTOOLS_SCM_PRETEND_VERSION=${{ version }} ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
        - numpy
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - cython >=0.29.23
    - numpy >=2.1.0
    - setuptools >=65.0.0
    - pip
  run:
    - lxml >=6.1.0
    - python
    - matplotlib-base >=3.8
    - monty >=2026.7.16
    - networkx >=2.7
    - orjson >=3.10,<4
    - palettable >=3.3.3
    - pandas >=2
    - scipy >=1.13.0
    - if: win
      then: scipy >=1.14.1
    - spglib >=2.5
    - sympy >=1.3
    - uncertainties >=3.1
    - plotly >=5.0
    - joblib >=1.3.2
    - bibtexparser
    - tabulate >=0.9.0
    - tqdm >=4.67.3
    - requests >=2.32.5
    - numpy
tests:
  - python:
      imports:
        - pymatgen
      pip_check: true

about:
  summary: Python Materials Genomics is a robust materials analysis code that defines core object representations for structures
  license: MIT
  license_file: LICENSE
  homepage: https://pymatgen.org

extra:
  recipe-maintainers:
    - jan-janssen
